apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: petclinic-db-secret
        image: postgres:18.4
        imagePullPolicy: IfNotPresent
        name: postgresql
        volumeMounts:
        - mountPath: /var/lib/postgres
          name: pvcmount
          resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: db-storage-volume
          persistentVolumeClaim:
            claimName: db-pvc
