apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-demo
  name: petclinic-demo
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: petclinic-demo
  template:
    metadata:
      labels:
        app: petclinic-demo
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: postgres
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db:5432/petclinic
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: petclinic-db-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: petclinic-db-secret
        image: petclinic:latest
        imagePullPolicy: IfNotPresent
        name: petclinic
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

