apiVersion: v1
data:
  POSTGRES_DB: cGV0Y2xpbmlj
  POSTGRES_PASSWORD: cGV0Y2xpbmlj
  POSTGRES_USER: cGV0Y2xpbmlj
kind: Secret
metadata:
  creationTimestamp: "2026-09-12T15:22:25Z"
  name: petclinic-db-secret
  namespace: default
  resourceVersion: "44951"
  uid: 1f5bf2db-d023-47fa-88e9-e9d964c2f8f5
type: Opaque
