apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-demo
  name: petclinic-svc
spec:
  ports:
  - nodePort: 32602
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-demo
  type: NodePort
